// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package terminator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"ztna-core/ztna/controller/rest_model"
)

// NewCreateTerminatorParams creates a new CreateTerminatorParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateTerminatorParams() *CreateTerminatorParams {
    logtrace.LogWithFunctionName()
	return &CreateTerminatorParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTerminatorParamsWithTimeout creates a new CreateTerminatorParams object
// with the ability to set a timeout on a request.
func NewCreateTerminatorParamsWithTimeout(timeout time.Duration) *CreateTerminatorParams {
    logtrace.LogWithFunctionName()
	return &CreateTerminatorParams{
		timeout: timeout,
	}
}

// NewCreateTerminatorParamsWithContext creates a new CreateTerminatorParams object
// with the ability to set a context for a request.
func NewCreateTerminatorParamsWithContext(ctx context.Context) *CreateTerminatorParams {
    logtrace.LogWithFunctionName()
	return &CreateTerminatorParams{
		Context: ctx,
	}
}

// NewCreateTerminatorParamsWithHTTPClient creates a new CreateTerminatorParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateTerminatorParamsWithHTTPClient(client *http.Client) *CreateTerminatorParams {
    logtrace.LogWithFunctionName()
	return &CreateTerminatorParams{
		HTTPClient: client,
	}
}

/* CreateTerminatorParams contains all the parameters to send to the API endpoint
   for the create terminator operation.

   Typically these are written to a http.Request.
*/
type CreateTerminatorParams struct {

	/* Terminator.

	   A terminator to create
	*/
	Terminator *rest_model.TerminatorCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create terminator params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateTerminatorParams) WithDefaults() *CreateTerminatorParams {
    logtrace.LogWithFunctionName()
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create terminator params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateTerminatorParams) SetDefaults() {
    logtrace.LogWithFunctionName()
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create terminator params
func (o *CreateTerminatorParams) WithTimeout(timeout time.Duration) *CreateTerminatorParams {
    logtrace.LogWithFunctionName()
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create terminator params
func (o *CreateTerminatorParams) SetTimeout(timeout time.Duration) {
    logtrace.LogWithFunctionName()
	o.timeout = timeout
}

// WithContext adds the context to the create terminator params
func (o *CreateTerminatorParams) WithContext(ctx context.Context) *CreateTerminatorParams {
    logtrace.LogWithFunctionName()
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create terminator params
func (o *CreateTerminatorParams) SetContext(ctx context.Context) {
    logtrace.LogWithFunctionName()
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create terminator params
func (o *CreateTerminatorParams) WithHTTPClient(client *http.Client) *CreateTerminatorParams {
    logtrace.LogWithFunctionName()
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create terminator params
func (o *CreateTerminatorParams) SetHTTPClient(client *http.Client) {
    logtrace.LogWithFunctionName()
	o.HTTPClient = client
}

// WithTerminator adds the terminator to the create terminator params
func (o *CreateTerminatorParams) WithTerminator(terminator *rest_model.TerminatorCreate) *CreateTerminatorParams {
    logtrace.LogWithFunctionName()
	o.SetTerminator(terminator)
	return o
}

// SetTerminator adds the terminator to the create terminator params
func (o *CreateTerminatorParams) SetTerminator(terminator *rest_model.TerminatorCreate) {
    logtrace.LogWithFunctionName()
	o.Terminator = terminator
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTerminatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Terminator != nil {
		if err := r.SetBodyParam(o.Terminator); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
