// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package terminator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"ztna-core/ztna/controller/rest_model"
)

// NewUpdateTerminatorParams creates a new UpdateTerminatorParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateTerminatorParams() *UpdateTerminatorParams {
    logtrace.LogWithFunctionName()
	return &UpdateTerminatorParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateTerminatorParamsWithTimeout creates a new UpdateTerminatorParams object
// with the ability to set a timeout on a request.
func NewUpdateTerminatorParamsWithTimeout(timeout time.Duration) *UpdateTerminatorParams {
    logtrace.LogWithFunctionName()
	return &UpdateTerminatorParams{
		timeout: timeout,
	}
}

// NewUpdateTerminatorParamsWithContext creates a new UpdateTerminatorParams object
// with the ability to set a context for a request.
func NewUpdateTerminatorParamsWithContext(ctx context.Context) *UpdateTerminatorParams {
    logtrace.LogWithFunctionName()
	return &UpdateTerminatorParams{
		Context: ctx,
	}
}

// NewUpdateTerminatorParamsWithHTTPClient creates a new UpdateTerminatorParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateTerminatorParamsWithHTTPClient(client *http.Client) *UpdateTerminatorParams {
    logtrace.LogWithFunctionName()
	return &UpdateTerminatorParams{
		HTTPClient: client,
	}
}

/* UpdateTerminatorParams contains all the parameters to send to the API endpoint
   for the update terminator operation.

   Typically these are written to a http.Request.
*/
type UpdateTerminatorParams struct {

	/* ID.

	   The id of the requested resource
	*/
	ID string

	/* Terminator.

	   A terminator update object
	*/
	Terminator *rest_model.TerminatorUpdate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update terminator params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateTerminatorParams) WithDefaults() *UpdateTerminatorParams {
    logtrace.LogWithFunctionName()
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update terminator params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateTerminatorParams) SetDefaults() {
    logtrace.LogWithFunctionName()
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update terminator params
func (o *UpdateTerminatorParams) WithTimeout(timeout time.Duration) *UpdateTerminatorParams {
    logtrace.LogWithFunctionName()
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update terminator params
func (o *UpdateTerminatorParams) SetTimeout(timeout time.Duration) {
    logtrace.LogWithFunctionName()
	o.timeout = timeout
}

// WithContext adds the context to the update terminator params
func (o *UpdateTerminatorParams) WithContext(ctx context.Context) *UpdateTerminatorParams {
    logtrace.LogWithFunctionName()
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update terminator params
func (o *UpdateTerminatorParams) SetContext(ctx context.Context) {
    logtrace.LogWithFunctionName()
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update terminator params
func (o *UpdateTerminatorParams) WithHTTPClient(client *http.Client) *UpdateTerminatorParams {
    logtrace.LogWithFunctionName()
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update terminator params
func (o *UpdateTerminatorParams) SetHTTPClient(client *http.Client) {
    logtrace.LogWithFunctionName()
	o.HTTPClient = client
}

// WithID adds the id to the update terminator params
func (o *UpdateTerminatorParams) WithID(id string) *UpdateTerminatorParams {
    logtrace.LogWithFunctionName()
	o.SetID(id)
	return o
}

// SetID adds the id to the update terminator params
func (o *UpdateTerminatorParams) SetID(id string) {
    logtrace.LogWithFunctionName()
	o.ID = id
}

// WithTerminator adds the terminator to the update terminator params
func (o *UpdateTerminatorParams) WithTerminator(terminator *rest_model.TerminatorUpdate) *UpdateTerminatorParams {
    logtrace.LogWithFunctionName()
	o.SetTerminator(terminator)
	return o
}

// SetTerminator adds the terminator to the update terminator params
func (o *UpdateTerminatorParams) SetTerminator(terminator *rest_model.TerminatorUpdate) {
    logtrace.LogWithFunctionName()
	o.Terminator = terminator
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateTerminatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Terminator != nil {
		if err := r.SetBodyParam(o.Terminator); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
