// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package link

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"ztna-core/ztna/controller/rest_model"
)

// NewPatchLinkParams creates a new PatchLinkParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchLinkParams() *PatchLinkParams {
    logtrace.LogWithFunctionName()
	return &PatchLinkParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchLinkParamsWithTimeout creates a new PatchLinkParams object
// with the ability to set a timeout on a request.
func NewPatchLinkParamsWithTimeout(timeout time.Duration) *PatchLinkParams {
    logtrace.LogWithFunctionName()
	return &PatchLinkParams{
		timeout: timeout,
	}
}

// NewPatchLinkParamsWithContext creates a new PatchLinkParams object
// with the ability to set a context for a request.
func NewPatchLinkParamsWithContext(ctx context.Context) *PatchLinkParams {
    logtrace.LogWithFunctionName()
	return &PatchLinkParams{
		Context: ctx,
	}
}

// NewPatchLinkParamsWithHTTPClient creates a new PatchLinkParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchLinkParamsWithHTTPClient(client *http.Client) *PatchLinkParams {
    logtrace.LogWithFunctionName()
	return &PatchLinkParams{
		HTTPClient: client,
	}
}

/* PatchLinkParams contains all the parameters to send to the API endpoint
   for the patch link operation.

   Typically these are written to a http.Request.
*/
type PatchLinkParams struct {

	/* ID.

	   The id of the requested resource
	*/
	ID string

	/* Link.

	   A link patch object
	*/
	Link *rest_model.LinkPatch

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchLinkParams) WithDefaults() *PatchLinkParams {
    logtrace.LogWithFunctionName()
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchLinkParams) SetDefaults() {
    logtrace.LogWithFunctionName()
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch link params
func (o *PatchLinkParams) WithTimeout(timeout time.Duration) *PatchLinkParams {
    logtrace.LogWithFunctionName()
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch link params
func (o *PatchLinkParams) SetTimeout(timeout time.Duration) {
    logtrace.LogWithFunctionName()
	o.timeout = timeout
}

// WithContext adds the context to the patch link params
func (o *PatchLinkParams) WithContext(ctx context.Context) *PatchLinkParams {
    logtrace.LogWithFunctionName()
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch link params
func (o *PatchLinkParams) SetContext(ctx context.Context) {
    logtrace.LogWithFunctionName()
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch link params
func (o *PatchLinkParams) WithHTTPClient(client *http.Client) *PatchLinkParams {
    logtrace.LogWithFunctionName()
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch link params
func (o *PatchLinkParams) SetHTTPClient(client *http.Client) {
    logtrace.LogWithFunctionName()
	o.HTTPClient = client
}

// WithID adds the id to the patch link params
func (o *PatchLinkParams) WithID(id string) *PatchLinkParams {
    logtrace.LogWithFunctionName()
	o.SetID(id)
	return o
}

// SetID adds the id to the patch link params
func (o *PatchLinkParams) SetID(id string) {
    logtrace.LogWithFunctionName()
	o.ID = id
}

// WithLink adds the link to the patch link params
func (o *PatchLinkParams) WithLink(link *rest_model.LinkPatch) *PatchLinkParams {
    logtrace.LogWithFunctionName()
	o.SetLink(link)
	return o
}

// SetLink adds the link to the patch link params
func (o *PatchLinkParams) SetLink(link *rest_model.LinkPatch) {
    logtrace.LogWithFunctionName()
	o.Link = link
}

// WriteToRequest writes these params to a swagger request
func (o *PatchLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Link != nil {
		if err := r.SetBodyParam(o.Link); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
